networks:
  caddy-net:
    driver: bridge
    ipam:
      config:
        - gateway: 172.18.0.1
          ip_range: 172.18.0.0/24
          subnet: 172.18.0.0/24
    name: caddy-net
  proxy-net:
    driver: bridge
    internal: true
    ipam:
      config:
        - gateway: 172.18.1.1
          ip_range: 172.18.1.0/24
          subnet: 172.18.1.0/24
    name: portainer_sp_net

services:
  portainer:
    cap_drop:
      - ALL
    command: -H tcp://portainer-socket-proxy:2375
    container_name: portainer
    dns: 172.18.0.2
    depends_on:
      portainer-socket-proxy:
        condition: service_healthy
    expose:
      - 9000
    healthcheck:
      test: ["CMD-SHELL", "wget --spider --no-verbose http://localhost:9000 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    hostname: portainer
    image: portainer/portainer-ce:2.40.0-alpine@sha256:bb1730d6411adc64328825897220e7711ad97f73e3c3638f8f2d71e9d2ddb2e7
    labels:
      - 'wud.display.icon=sh:portainer'
      - 'wud.tag.include=^\d+\.\d+\.\d+-alpine$$'
      - 'wud.link.template=https://github.com/portainer/portainer/releases/tag/$${major}.$${minor}.$${patch}'
    networks:
      caddy-net:
        ipv4_address: 172.18.0.20
      proxy-net:
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /tmp:mode=1777,noexec,nosuid,nodev
      - /run:mode=0755,nosuid,nodev
      - /var/run:mode=0755,nosuid,nodev
    user: "1000:1000"
    volumes:
      - portainer_data:/data

  portainer-socket-proxy:
    cap_drop:
      - ALL
    container_name: portainer-socket-proxy
    environment:
      - AUTH=0
      - BUILD=0
      - COMMIT=0
      - CONFIGS=0
      - CONTAINERS=1
      - DISABLE_IPV6=0
      - DISTRIBUTION=0
      - EVENTS=1
      - EXEC=0
      - IMAGES=1
      - INFO=1
      - LOG_LEVEL=notice
      - NETWORKS=1
      - NODES=0
      - PING=1
      - PLUGINS=0
      - POST=1
      - SECRETS=0
      - SERVICES=0
      - SESSION=0
      - SOCKET_PATH=/var/run/docker.sock
      - SWARM=0
      - SYSTEM=1
      - TASKS=0
      - TZ=${TZ}
      - VERSION=1
      - VOLUMES=1
    expose:
      - 2375
    healthcheck:
      test: ["CMD-SHELL", "wget --spider --no-verbose http://localhost:2375/_ping || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    hostname: portainer-socket-proxy
    image: linuxserver/socket-proxy:3.2.16@sha256:10736f397ddee2775754dcbffe1e4cf27e9b3d91917c471da9cfc1cd9ce9d186
    labels:
      - 'wud.tag.include=^\d+\.\d+\.\d+\-r\d\-ls\d+$$'
      - 'wud.link.template=https://github.com/linuxserver/docker-socket-proxy/releases/tag/$${raw}'
    networks:
      proxy-net:
    read_only: true
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /run:exec
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

volumes:
  portainer_data:
