networks:
  caddy-net:
    name: caddy-net
    external: true

services:
  drawio:
    cap_drop:
      - ALL
    container_name: drawio
    dns: 172.19.0.2
    deploy:
      resources:
        limits:
          memory: 256M
    expose:
      - 8080
    healthcheck:
      test: ["CMD-SHELL", "wget -q -O /dev/null http://127.0.0.1:8080/healthz || exit 1"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s
    hostname: drawio
    image: ghcr.io/mmichalak-swe/homelab-gitops/drawio:31.3.1-alpine-custom@sha256:37ed0e106e7076477e8270fc4112dbce3fdd4ce409e832b2e643b72c7a4ee95c
    networks:
      caddy-net:
        ipv4_address: 172.19.0.22
    read_only: true
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /tmp:rw,noexec,nosuid,nodev,size=64m
