networks:
  caddy-net:
    name: caddy-net
    external: true

services:
  pihole-gmkg3:
    cap_add:
      - CHOWN
      - DAC_OVERRIDE
      - FOWNER
      - NET_BIND_SERVICE
      - SETFCAP
      - SETUID
      - SETGID
    cap_drop:
      - ALL
    container_name: pihole-gmkg3
    depends_on:
      unbound:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 512M
    environment:
      - DNSMASQ_USER=${DNSMASQ_USER}
      - FTLCONF_dns_bogusPriv=${FTLCONF_dns_bogusPriv}
      - FTLCONF_dns_dnssec=${FTLCONF_dns_dnssec}
      - FTLCONF_dns_domainNeeded=${FTLCONF_dns_domainNeeded}
      - FTLCONF_dns_listeningMode=${FTLCONF_dns_listeningMode}
      - FTLCONF_dns_upstreams=${FTLCONF_dns_upstreams}
      - FTLCONF_webserver_api_password=${FTLCONF_webserver_api_password}
      - PIHOLE_GID=${PIHOLE_GID}
      - PIHOLE_UID=${PIHOLE_UID}
      - TZ=${TZ}
    expose:
      - 80
    hostname: pihole-gmkg3
    image: pihole/pihole:2026.05.0@sha256:70a9c11171ded2eee735d88c127996da209284a329d50f5ae59c06b861d401b3
    networks:
      caddy-net:
        ipv4_address: 172.19.0.2
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    read_only: false
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /tmp
      - /run
      - /var/run
      - /var/log/pihole
    volumes:
      - etc-pihole:/etc/pihole


  unbound:
    cap_drop:
      - ALL
    container_name: unbound
    deploy:
      resources:
        limits:
          memory: 256M
    healthcheck:
      test: ['CMD', 'drill-hc', '@172.19.0.3', 'dnssec.works']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    hostname: unbound
    image: klutchell/unbound:1.25.1@sha256:4718d579152d49a3eaf7cbc1ce67f4e2e0d6f396be8f604a2416a94e7a250be8
    networks:
      caddy-net:
        ipv4_address: 172.19.0.3
    read_only: true
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    user: "101:102"
    volumes:
      - unbound-config:/etc/unbound


volumes:
  etc-pihole:
  unbound-config:
