networks:
  caddy-net:
    name: caddy-net
    external: true
  wg-ls-net:
    name: wg_net
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.10.0/24
          ip_range: 172.18.10.0/24
          gateway: 172.18.10.1

services:
  wireguard-ls:
    cap_add:
      - CHOWN
      - DAC_OVERRIDE
      - FOWNER
      - NET_ADMIN
    cap_drop:
      - ALL
    container_name: wireguard-ls
    deploy:
      resources:
        limits:
          memory: 256M
    dns: 172.18.0.2
    environment:
      - ALLOWEDIPS=${ALLOWEDIPS}
      - INTERNAL_SUBNET=${INTERNAL_SUBNET}
      - LOG_CONFS=${LOG_CONFS}
      - PEERS=${PEERS}
      - PEERDNS=${PEERDNS}
      - PERSISTENTKEEPALIVE_PEERS=${PERSISTENTKEEPALIVE_PEERS}
      - SERVERPORT=${SERVERPORT}
      - SERVERURL=${SERVERURL}
      - TZ=${TZ}
    healthcheck:
      test: ["CMD-SHELL", "ip link show wg0 &> /dev/null || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    hostname: wireguard-ls
    image: linuxserver/wireguard:1.0.20250521@sha256:8e505886ba5da6788f1b9dfc62a25e2f2c3a96e64e6528ef7278d7e1d6649bd2
    labels:
      - 'wud.display.icon=sh:wireguard'
      - 'wud.tag.include=^\d+\.\d+\.\d+\-r\d\-ls\d{3,}$$'
      - 'wud.link.template=https://github.com/linuxserver/docker-wireguard/releases/tag/$${raw}'
    networks:
      wg-ls-net:
        ipv4_address: 172.18.10.2
        gw_priority: 1
      caddy-net:
        ipv4_address: 172.18.0.6
        gw_priority: 0
    ports:
      - ${SERVERPORT}:51820/udp
    read_only: true
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    tmpfs:
      - /run:exec
      - /tmp
    volumes:
      - config:/config

volumes:
  config:
