networks:
  caddy-net:
    name: caddy-net
    external: true

services:
  vaultwarden:
    cap_drop:
      - ALL
    container_name: vaultwarden
    deploy:
      resources:
        limits:
          memory: 256M
    dns: 172.18.0.2
    environment:
      - DOMAIN=${DOMAIN}
    expose:
      - 80
    hostname: vaultwarden
    image: vaultwarden/server:1.37.3-alpine@sha256:9a905c5cf5df61bb827da3805e160170741c0b53b0c63bb07e1afd3d2e21b1c8
    networks:
      caddy-net:
        ipv4_address: 172.18.0.21
    read_only: true
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /tmp
      - /run
      - /var/run
    user: "1000:1000"
    volumes:
      - data:/data/

volumes:
  data:
