networks:
  caddy-net:
    name: caddy-net
    external: true

services:
  vaultwarden:
    cap_drop:
      - ALL
    container_name: vaultwarden
    deploy:
      resources:
        limits:
          memory: 256M
    dns: 172.18.0.2
    environment:
      - DOMAIN=${DOMAIN}
    expose:
      - 80
    hostname: vaultwarden
    image: vaultwarden/server:1.37.2-alpine@sha256:d16a304c2476fd787634ddde2c00be8fdfa1a72539438c626ece3686b5b88ab4
    networks:
      caddy-net:
        ipv4_address: 172.18.0.21
    read_only: true
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /tmp
      - /run
      - /var/run
    user: "1000:1000"
    volumes:
      - data:/data/

volumes:
  data:
