# https://github.com/oijkn/Docker-Raspberry-PI-Monitoring
networks:
  caddy-net:
    external: true
    name: caddy-net

  monitoring-internal:
    driver: bridge
    internal: true
    ipam:
      config:
        - gateway: 172.18.3.1
          ip_range: 172.18.3.0/24
          subnet: 172.18.3.0/24
    name: monitoring_net

services:
  cadvisor:
    command:
      - '-docker_only=true'
      - '-housekeeping_interval=15s'
      - '-store_container_labels=false'
    container_name: monitoring-cadvisor
    devices:
      - /dev/kmsg
    expose:
      - 8080
    hostname: monitoring-cadvisor
    image: ghcr.io/google/cadvisor:0.56.2
    labels:
      - 'wud.display.icon=sh:cadvisor'
      - 'wud.tag.include=^v\d+(?:\.\d{1,2})?\.\d+$$'
      - 'wud.link.template=https://github.com/google/cadvisor/releases/tag/v$${major}.$${minor}.$${patch}'
    logging:
      driver: json-file
      options:
        max-size: "128m"
    networks:
      monitoring-internal:
    privileged: true
    restart: unless-stopped
    volumes:
      - /:/rootfs:ro
      - /dev/disk/:/dev/disk:ro
      - /etc/machine-id:/etc/machine-id:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /var/run:/var/run:ro

  grafana:
    container_name: monitoring-grafana
    depends_on:
      prometheus:
        condition: service_healthy
    dns: 172.18.0.2
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
      - GF_USERS_ALLOW_SIGN_UP=${GF_USERS_ALLOW_SIGN_UP}
      - GF_PATHS_CONFIG=${GF_PATHS_CONFIG}
      - GF_PATHS_DATA=${GF_PATHS_DATA}
      - GF_PATHS_HOME=${GF_PATHS_HOME}
      - GF_PATHS_LOGS=${GF_PATHS_LOGS}
      - GF_PATHS_PLUGINS=${GF_PATHS_PLUGINS}
      - GF_PATHS_PROVISIONING=${GF_PATHS_PROVISIONING}
      - GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH=${GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH}
    expose:
      - 3000
    healthcheck:
      test: curl -f http://localhost:3000/api/health || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    hostname: monitoring-grafana
    image: grafana/grafana:12.4.1
    labels:
      - 'wud.display.icon=sh:grafana'
      - 'wud.tag.include=^\d+\.\d+\.\d+$$'
      - 'wud.link.template=https://github.com/grafana/grafana/releases/tag/v$${major}.$${minor}.$${patch}'
    logging:
      driver: json-file
      options:
        max-size: "128m"
    networks:
      caddy-net:
        ipv4_address: 172.18.0.11
      monitoring-internal:
    restart: unless-stopped
    user: "472"
    volumes:
      - grafana-data:/var/lib/grafana
      - grafana-prov:/etc/grafana/provisioning:ro

  node-exporter:
    command:
      - --collector.filesystem.ignored-mount-points
      - ^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)
      - --path.procfs=/host/proc
      - --path.rootfs=/host
      - --path.sysfs=/host/sys
    container_name: monitoring-node-exporter
    expose:
      - 9100
    healthcheck:
      test: ["CMD-SHELL", "wget --spider --quiet http://localhost:9100/metrics || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    hostname: monitoring-exporter
    image: prom/node-exporter:v1.10.2
    labels:
      - 'wud.tag.include=^v\d+\.\d+\.\d+$$'
      - 'wud.link.template=https://github.com/prometheus/node_exporter/releases/tag/v$${major}.$${minor}.$${patch}'
    logging:
      driver: json-file
      options:
        max-size: "128m"
    networks:
      monitoring-internal:
    restart: unless-stopped
    volumes:
      - /:/host:ro,rslave
      - /:/rootfs:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro

  prometheus:
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.size=10GB'
      - '--storage.tsdb.retention.time=1y'
    container_name: monitoring-prometheus
    depends_on:
      cadvisor:
        condition: service_healthy
      node-exporter:
        condition: service_healthy
    expose:
      - 9090
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://127.0.0.1:9090/-/healthy || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    hostname: monitoring-prometheus
    image: prom/prometheus:v3.10.0
    labels:
      - 'wud.display.icon=sh:prometheus'
      - 'wud.tag.include=^v\d+\.\d+\.\d+$$'
      - 'wud.link.template=https://github.com/prometheus/prometheus/releases/tag/v$${major}.$${minor}.$${patch}'
    logging:
      driver: json-file
      options:
        max-size: "128m"
    networks:
      monitoring-internal:
    restart: unless-stopped
    user: "nobody"
    volumes:
      - prom-etc:/etc/prometheus:ro
      - prom-data:/prometheus

volumes:
  grafana-data:
  grafana-prov:
  prom-data:
  prom-etc:
